services:
  marketplace:
    build: .
    container_name: marketplace-api
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: marketplace-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - marketplace
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: marketplace-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email leoncoolio@gmail.com
      --agree-tos
      --no-eff-email
      -d api.vuzy.eu"
