version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: marketplace_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: marketplace_redis_dev
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_dev_data:
